[shell]
fish_indicator = "ğŸŸ"
bash_indicator = "ğŸ‘Š"

[kubernetes]
disabled = false
format = 'on [â›µ $context ](dimmed green) '
[kubernetes.context_aliases]
"redikube-eastus-dev" = "dev"
"redikube-eastus-prod" = "prod"
"redikube-eastus-redisite" = "redisite"
"redikube-eastus-prod-admin" = "prod-admin"
"redikube-eastus-dev-admin" = "dev-admin"
"redikube-eastus-redisite-admin" = "redisite-admin"
"kind-kind" = "local"

[time]
disabled = false
format = 'ğŸ•™[\[ $time \]]($style) '
utc_time_offset = "-5"

[helm]
format = "via [âˆ $version](bold white) "

[terraform]
format = '[ğŸğŸ’¨ $version$workspace]($style) '

[status]
style = "bg:blue"
symbol = "ğŸ”´"
format = '[\[$symbol $status_common_meaning$status_signal_name$status_maybe_int\]]($style) '
map_symbol = true
disabled = false
